### ISSUE TITLE
Server error, private key not found when requesting access_token

### ISSUE THREAD

**Issue by stephancill** [bitnami/bitnami-docker-suitecrm#128]
**Description**
A server error is produced when following the steps to add SuiteCRM API support in the readme. I have checked and the keys are being created in the correct directory by the Dockerfile command.

**Steps to reproduce the issue:**

1. Copy docker-compose.yml from the [template](https://github.com/bitnami/bitnami-docker-suitecrm/blob/master/docker-compose.yml)
2. Replace the suitecrm service's image key with `build: .`
3. Copy Dockerfile from [Example 2](https://github.com/bitnami/bitnami-docker-suitecrm#example-2-add-suitecrm-api-support)
4. Run `docker-compose up` and wait for setup to complete
5. Log in with username `user` and password `bitnami`
6. Navigate to Admin > OAuth2 Clients and Tokens (/index.php?module=OAuth2Clients&action=index)
7. Create a new Client Credentials Client
8. Execute a POST request to /Api/access_token with JSON body
```
{
    "grant_type": "client_credentials",
    "client_id": "<CLIENT_ID>",
    "client_secret": "<CLIENT_SECRET>"
}
```

**Describe the results you received:**

Server error with the following logs:
```
suitecrm_1  | [Fri Jan 22 11:22:18.310879 2021] [php7:error] [pid 167] [client 197.94.92.183:29092] PHP Fatal error:  Uncaught LogicException: Key path "file:///bitnami/suitecrm/Api/V8/OAuth2/private.key" does not exist or is not readable in /bitnami/suitecrm/vendor/league/oauth2-server/src/CryptKey.php:45\nStack trace:\n#0 /bitnami/suitecrm/vendor/league/oauth2-server/src/AuthorizationServer.php(99): League\\OAuth2\\Server\\CryptKey->__construct('file:///bitnami...')\n#1 /bitnami/suitecrm/Api/V8/Config/services/middlewares.php(35): League\\OAuth2\\Server\\AuthorizationServer->__construct(Object(Api\\V8\\OAuth2\\Repository\\ClientRepository), Object(Api\\V8\\OAuth2\\Repository\\AccessTokenRepository), Object(Api\\V8\\OAuth2\\Repository\\ScopeRepository), 'file:///bitnami...', 'file:///bitnami...')\n#2 /bitnami/suitecrm/vendor/pimple/pimple/src/Pimple/Container.php(118): Api\\Core\\Resolver\\ConfigResolver::{closure}(Object(Slim\\Container))\n#3 /bitnami/suitecrm/vendor/slim/slim/Slim/Container.php(109): Pimple\\Container->offsetGet('League\\\\OAuth2\\\\S...')\n#4 /bitnami/suitecrm/Api/V8/Config/routes.php(17): Slim\\Container->get('League\\\\OAuth2\\\\S...')\n#5  in /bitnami/suitecrm/vendor/league/oauth2-server/src/CryptKey.php on line 45
suitecrm_1  | 197.94.92.183 - - [22/Jan/2021:11:22:18 +0000] "POST /Api/access_token HTTP/1.1" 500 -
```

**Describe the results you expected:**

Response with access_token

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 981.3MiB
 Name: docker-s-1vcpu-1gb-ams3-01
 ID: YVPQ:U62Z:WQXU:FNCP:HLHI:GDT5:Z3BR:7POI:NN7S:YF4E:JYKZ:3IRZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Ubuntu 20.04

**Comment by andresbono** [comment]
Hi @stephancill, it seems a permissions issue. Could you try this `Dockerfile` instead?

```Dockerfile
FROM bitnami/suitecrm
LABEL maintainer "Bitnami <containers@bitnami.com>"
## Install keys
RUN openssl genrsa -out /opt/bitnami/suitecrm/Api/V8/OAuth2/private.key 2048 && \
    openssl rsa -in /opt/bitnami/suitecrm/Api/V8/OAuth2/private.key -pubout -out /opt/bitnami/suitecrm/Api/V8/OAuth2/public.key && \
    chmod 640 /opt/bitnami/suitecrm/Api/V8/OAuth2/private.key && \
    chown :daemon /opt/bitnami/suitecrm/Api/V8/OAuth2/private.key /opt/bitnami/suitecrm/Api/V8/OAuth2/public.key
```

SuiteCRM is running as `root` by default, and executes the Apache process as `daemon`.

Let us know if this new Dockerfile works for you and we will update the documentation.

**Comment by stephancill** [comment]
@andresbono Worked perfectly. Thanks a lot!

**Comment by andresbono** [comment]
That's great, @stephancill! We will update the documentation.

**Comment by officialasit** [comment]
Also on performing a docker log I found this error while requesting:
```
PHP Fatal error:  Uncaught LogicException: Key path "file:///bitnami/suitecrm/Api/V8/OAuth2/private.key" does not exist or is not readable in /bitnami/suitecrm/vendor/league/oauth2-server/src/CryptKey.php:45\nStack trace:\n#0 /bitnami/suitecrm/Api/V8/Config/services/middlewares.php(39): League\\OAuth2\\Server\\CryptKey->__construct('file:///bitnami...', NULL, true)\n#1 /bitnami/suitecrm/vendor/pimple/pimple/src/Pimple/Container.php(118): Api\\Core\\Resolver\\ConfigResolver::{closure}(Object(Slim\\Container))\n#2 /bitnami/suitecrm/vendor/slim/slim/Slim/Container.php(109): Pimple\\Container->offsetGet('League\\\\OAuth2\\\\S...')\n#3 /bitnami/suitecrm/Api/V8/Config/routes.php(17): Slim\\Container->get('League\\\\OAuth2\\\\S...')\n#4 /bitnami/suitecrm/vendor/slim/slim/Slim/RouteGroup.php(25): Api\\Core\\Loader\\RouteLoader->{closure}(Object(Slim\\App))\n#5 /bitnami/suitecrm/vendor/slim/slim/Slim/App.php(272): Slim\\RouteGroup->__invoke(Object(Slim\\App))\n#6 /bitnami/suitecrm/Api/V8/Config/routes.php(132): Slim\\App->group('', Object(Closure))\n#7 /bitnami/suitec in /bitnami/suitecrm/vendor/league/oauth2-server/src/CryptKey.php on line 45
```

**Comment by alemorcuq** [comment]
Hi, @officialasit. Using the same Dockerfile and docker-compose.yml files you shared I'm not able to reproduce the issue:

```
❯ curl -d '{"grant_type":"client_credentials", "client_id":"6eb10d3a-d139-f3f8-173b-60c063a746bb", "client_secret":"hola"}' -H "Content-Type: application/json" -X POST http://127.0.0.1:8080/Api/access_token
{"token_type":"Bearer","expires_in":3600,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImViMzMzZDYzZmVjYzdlN2QxOTVjOTQwZTdmNTNmMjFlNmU5NTY2OTU4NDY4ZGU3NjUyMTFlODc3ZjJmZDQxOTA1NTAwNmZkM2MzNjM5NTA1In0.eyJhdWQiOiI2ZWIxMGQzYS1kMTM5LWYzZjgtMTczYi02MGMwNjNhNzQ2YmIiLCJqdGkiOiJlYjMzM2Q2M2ZlY2M3ZTdkMTk1Yzk0MGU3ZjUzZjIxZTZlOTU2Njk1ODQ2OGRlNzY1MjExZTg3N2YyZmQ0MTkwNTUwMDZmZDNjMzYzOTUwNSIsImlhdCI6MTYyMzIyMTIzMywibmJmIjoxNjIzMjIxMjMzLCJleHAiOjE2MjMyMjQ4MzMsInN1YiI6IiIsInNjb3BlcyI6W119.ZYc9snk7aTCfgKJOX2J3MP6bqKH7ZSPR3iCsW7CZ6lSreIRLqEw4G5D8uCmP_3UXccazUgq_G2j0N9Lej6MO5Sq2Iq0Sd19-nl5C9o31V3xIH8PsXqxuFcfWK59yETFYOR6YwRLJP5l0KRj8YUEiJnD4C1ervZtl8UA3Mq65tLFGELpziUYKe3SR6IRBCpmA1A3HyZfkuD8NXkcDNeDP_a8XnrvIPxGPD5oOVCqYl5eDxqRMjh_6lFtQBqQwKZplOchR3aDeuiD25yhvjHI--fYejyEk2XqnI7wVY-TbNaVyuDdygRMxN_vHF5BKkcbtzE9kcQDPRwMbIEZtMry6mQ"}%
```

Please, check that this file exists in your container and has the right permissions: `/bitnami/suitecrm/Api/V8/OAuth2/private.key`.

**Comment by officialasit** [comment]
Got it solved by re-building image and giving permission by getting into docker-container. Thanks @alemorcuq
