### ISSUE TITLE
since 7.12.5-debian-10-r32, requesting an API token returns an error

### ISSUE THREAD

**Issue by stephlegrand** [bitnami/bitnami-docker-suitecrm#149]
### Name and Version

bitnami/suitecrm:7.12.5-debian-10-r32

### What steps will reproduce the bug?

I have been using the SuiteCRM V8 API for months and it works fine. I call it from n8n automations.

Suddenly it broke with bitnami/suitecrm:7.12.5-debian-10-r32

### What is the expected behavior?
```
{
  "token_type": "Bearer",
  "expires_in": 3600,
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImVlM2YyNzBiYzhlZjhiMTE2ZDYzMmEwMDczNTFiZGZlNThhYjI2OGJhMmZiYmIyMTFjNjFiNmZiY2Y1Njc4Mj [   redacted  ] 27oHRKXUG4tFHCcYs3SMJ_XHhTPvLdpPLvaoZ_gAdYqd0r1_zxLR4Q"
}
```
### What do you see instead?
```
{"status":"rejected","reason":{"message":"500 - {\"error\":\"unknown_error\",\"message\":\"It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line\"}","name":"Error","stack":"Error: Request failed with status code 500\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:538:35)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}}
```
### Additional information

This is happening with every version since 7.12.5-debian-10-r32. It is still broken with r35.

If I revert to r31, requesting a token works fine.

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-suitecrm#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by stephlegrand** [comment]
It is still broken with version 7.12.5-debian-10-**r42** (and still working fine with all versions up to r31)

I am on **Ubuntu 20.04**. Docker version is **20.10.14**

Output of docker info :

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 22
  Running: 22
  Paused: 0
  Stopped: 0
 Images: 25
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-107-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.585GiB
  
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
