### ISSUE TITLE
suitecrm 7.10.2-r1 timeout

### ISSUE THREAD

**Issue by LinforPros** [bitnami/bitnami-docker-suitecrm#77]
It is a new installation:
```
git clone https://(bitnami-suitecrm-git)
cd bitnami-docker-suitecrm/7
docker-compose up -d

[root@localhost 7]# docker-compose logs -f
Attaching to 7_suitecrm_1, 7_mariadb_1
mariadb_1   | 
mariadb_1   | Welcome to the Bitnami mariadb container
mariadb_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1   | Send us your feedback at containers@bitnami.com
mariadb_1   | 
mariadb_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1   | nami    INFO  Initializing mariadb
mariadb_1   | mariadb INFO  ==> Cleaning data dir...
mariadb_1   | mariadb INFO  ==> Configuring permissions...
mariadb_1   | mariadb INFO  ==> Validating inputs...
mariadb_1   | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1   | mariadb WARN  Allowing the "password" input to be empty
mariadb_1   | mariadb INFO  ==> Initializing database...
suitecrm_1  | 
suitecrm_1  | Welcome to the Bitnami suitecrm container
suitecrm_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-suitecrm
suitecrm_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-suitecrm/issues
suitecrm_1  | Send us your feedback at containers@bitnami.com
suitecrm_1  | 
suitecrm_1  | nami    INFO  Initializing apache
suitecrm_1  | apache  INFO  ==> Patching httpoxy...
suitecrm_1  | apache  TRACE [prepareDataToPersist] Preparing /opt/bitnami/apache/conf to persist in /bitnami/apache/conf
suitecrm_1  | nami    INFO  apache successfully initialized
suitecrm_1  | nami    INFO  Initializing php
suitecrm_1  | php     TRACE [prepareDataToPersist] Preparing /opt/bitnami/php/conf to persist in /bitnami/php/conf
suitecrm_1  | nami    INFO  php successfully initialized
suitecrm_1  | nami    INFO  Initializing mysql-client
suitecrm_1  | nami    INFO  mysql-client successfully initialized
mariadb_1   | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1   | mariadb INFO  ==> Creating database bitnami_suitecrm...
mariadb_1   | mariadb INFO  ==> Creating user bn_suitecrm...
mariadb_1   | mariadb INFO  ==> Granting access to bn_suitecrm to the database bitnami_suitecrm...
mariadb_1   | mariadb INFO  ==> Enabling remote connections...
suitecrm_1  | nami    INFO  Initializing suitecrm
suitecrm_1  | apache  TRACE Skipping reload: com.bitnami.apache not running
suitecrm_1  | apache  TRACE [runProgram] Executing: null /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
mariadb_1   | mariadb INFO 
mariadb_1   | mariadb INFO  ########################################################################
mariadb_1   | mariadb INFO   Installation parameters for mariadb:
mariadb_1   | mariadb INFO     Root User: root
mariadb_1   | mariadb INFO     Root Password: Not set during installation
mariadb_1   | mariadb INFO     Database: bitnami_suitecrm
mariadb_1   | mariadb INFO     Username: bn_suitecrm
mariadb_1   | mariadb INFO     Password: Not set during installation
mariadb_1   | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1   | mariadb INFO  ########################################################################
mariadb_1   | mariadb INFO 
mariadb_1   | nami    INFO  mariadb successfully initialized
mariadb_1   | INFO  ==> Starting mariadb... 
mariadb_1   | INFO  ==> Starting mysqld_safe...
mariadb_1   | 180320 02:15:51 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1   | 180320 02:15:51 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
suitecrm_1  | apache  TRACE code: 0
suitecrm_1  | apache  TRACE stdout:
suitecrm_1  | 
suitecrm_1  | apache  TRACE stderr:
suitecrm_1  | 
suitecrm_1  | suitecr INFO  Preparing webserver environment...
suitecrm_1  | apache  TRACE [runProgram] Executing: /opt/bitnami/apache/bin/apachectl graceful
suitecrm_1  | suitecr INFO  Preparing PHP environment...
suitecrm_1  | suitecr INFO  Preparing suitecrm environment...
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/cache
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/custom
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/modules
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/themes
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/data
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/upload
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/config.php
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/suitecrm.log
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/install.log
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/install/status.json
suitecrm_1  | suitecr TRACE [configurePermissions] File to chown: /opt/bitnami/suitecrm/.htaccess
suitecrm_1  | suitecr INFO  Configuring Database...
suitecrm_1  | mysql-c INFO  Trying to connect to MySQL server
suitecrm_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
suitecrm_1  | mysql-c TRACE [canConnect] Testing connection with 'bn_suitecrm' user
suitecrm_1  | mysql-c TRACE [showDatabases] Getting databases for 'bn_suitecrm' user
suitecrm_1  | mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hmariadb -ubn_suitecrm -e SHOW DATABASES;
suitecrm_1  | mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_suitecrm\ninformation_schema\n","stderr":""}
suitecrm_1  | mysql-c TRACE [showDatabases] Databases: bitnami_suitecrm
suitecrm_1  | information_schema
suitecrm_1  | 
suitecrm_1  | mysql-c TRACE [canConnect] Connection with 'bn_suitecrm' user is successful
suitecrm_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
suitecrm_1  | suitecr INFO  Configuring silent installation
suitecrm_1  | suitecr INFO  Installing suitecrm. It could take some minutes...
suitecrm_1  | Error executing 'postInstallation': Timeout: did not get to load all resources on this page
suitecrm_1  | nami    TRACE Error: Error executing 'postInstallation': Timeout: did not get to load all resources on this page
suitecrm_1  |     at Browser.exec (/opt/bitnami/nami/node_modules/nami-core/lib/browser/index.js:447:15)
suitecrm_1  |     at Object.$app.helpers.passWizard (/root/.nami/components/com.bitnami.suitecrm/helpers.js:24:69)
suitecrm_1  |     at Component.$app.postInstallation (/root/.nami/components/com.bitnami.suitecrm/main.js:101:20)
suitecrm_1  |     at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
suitecrm_1  |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
suitecrm_1  |     at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
suitecrm_1  |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
suitecrm_1  |     at Component.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
suitecrm_1  |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
suitecrm_1  |     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
suitecrm_1  |     at NamiParser.parseCommands (/opt/bitnami/nami/node_modules/cmd-parser/index.js:518:30)
suitecrm_1  |     at NamiParser.parse (/opt/bitnami/nami/node_modules/cmd-parser/index.js:742:14)
suitecrm_1  |     at NamiCliApp.parse (/opt/bitnami/nami/cli/nami-app.js:592:17)
suitecrm_1  |     at NamiCliApp.exec (/opt/bitnami/nami/cli/nami-app.js:599:12)
suitecrm_1  |     at Object.<anonymous> (/opt/bitnami/nami/index.js:10:19)
suitecrm_1  |     at Module._compile (module.js:541:32)
7_suitecrm_1 exited with code 1
```

The machine has the following installed:
```
docker-compose version 1.17.1, build 6d101fb
Docker version 18.02.0-ce, build fc4de44
docker info 
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 7
Server Version: 18.02.0-ce
Storage Driver: btrfs
 Build Version: Btrfs v4.11.1
 Library Version: 102
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.15.9-300.fc27.x86_64
Operating System: Fedora 27 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.15GiB
Name: localhost.localdomain
ID: ILI2:37U4:PVKO:66RE:IYKI:MN2Q:XIWR:5SA2:UF6K:EVAY:OGWA:VNPO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: linforpros
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Any idea why ?

**Comment by javsalgar** [comment]
Hi,

I tried to reproduce the issue and found some issues with selinux. I disabled the volumes but did not get the error you show me. Just in case, is selinux enabled? 

This is the docker version I used in the Fedora machine: 1.10.3. I also tried in 17.03 and found no issues. Could you check if the issue occurs in a previous docker version?

**Comment by Coolfeather2** [comment]
setting the following environment variables fixed it for me -  removed them after the initial install and its all working now
```
         - name: SUITECRM_HTTP_TIMEOUT
           value: "3600"
         - name: NAMI_DEBUG
           value: "--log-level trace"
```

**Comment by Coolfeather2** [comment]
Yep, that Variable is not necessary, used it to debug of it failed again

**Comment by javsalgar** [comment]
> used it to debug of it failed again

Could you confirm that using 3600 provides no issues? I did not fully understand this last part of the message

**Comment by Coolfeather2** [comment]
autocorrect...

**Comment by javsalgar** [comment]
Ok, so I understand it is fixed :D If you come across any other issues, do not hesitate to open a new ticket.
